<div class="evt_fixed_top_left">
	<a id="evt_fb" class="evt_social" href="https://www.facebook.com/EventBiller" target="_blank">facebook</a>
	<a id="evt_tw" class="evt_social" href="#" onclick="Popup=window.open('https://twitter.com/share','Popup','width=500,height=500'); return false;">twiter</a>
	<a id="evt_gp" class="evt_social" href="https://plus.google.com/u/0/115124321811991330705/posts" target="_blank">google+</a>
</div>