<div class="evt_hr"></div>
<div id="evt_footer">
	EventBiller is a service provided by JLG-Consulting&nbsp;-&nbsp;©2013<br/>
	<a href="info/terms">Terms and Conditions</a>&nbsp;|&nbsp;<a href="info/sales">Sales policies</a>&nbsp;|&nbsp;<a href="info/privacy">Privacy policies</a><br/>
	This web site is hosted with <a href="http://www.ovh.com" target="_blank">OVH</a>. For more security, you can use it with its <a href="<?php echo HTTPS_ACCESS.dirname($_SERVER['SCRIPT_NAME']); ?>">HTTPS access</a>.
	<?php layout_trace(); ?>
</div>
