<div class="evt_hr"></div>
<div id="evt_footer">
	{{Event-Biller is a service provided by JLG-Consulting}}&nbsp;-&nbsp;©2013<br/>
	<a href="info/terms">{{Terms and Conditions}}</a>&nbsp;|&nbsp;<a href="info/sales">{{Sales policies}}</a>&nbsp;|&nbsp;<a href="info/privacy">{{Privacy policies}}</a>&nbsp;|&nbsp;<a href="info/what_we_do">{{What we do}}</a><br/>
	<div id="evt_logo">
		<a href="http://paypal.com" target="_blank"><img src="<?php echo SKIN_DIR; ?>/images/paypal.gif" /><span class="spacer"></span><img src="<?php echo SKIN_DIR; ?>/images/cards.png" /></a>
		<span class="spacer"></span>
		<a href="http://bitcoin.org" target="_blank"><img src="<?php echo SKIN_DIR; ?>/images/bitcoin.png" /></a>
	</div>
	{{This web site is hosted with}} <a href="http://www.ovh.com" target="_blank">OVH</a>. {{You can also use it with its}} <a href="<?php echo HTTPS_ACCESS; ?>">{{HTTPS access}}</a>.
</div>